version: 0.2

phases:
  pre_build:
    commands:
      - echo "========== DEPLOYMENT PHASE STARTING =========="
      - echo "Installing Terraform..."
      - dnf install -y dnf-plugins-core
      - dnf config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - dnf install -y terraform
      - terraform --version
  build:
    commands:
      - echo "========== CURRENT DIRECTORY =========="
      - pwd
      - ls -la
      - echo "========== APPLYING TERRAFORM =========="
      - terraform init
      - terraform apply -auto-approve -input=false
  post_build:
    commands:
      - echo "========== DEPLOYMENT COMPLETE =========="
      - echo "Infrastructure successfully deployed!"
