version: 0.2

phases:
  install:
    commands:
      - echo '========== INSTALLING DEPENDENCIES =========='
      - dnf install -y dnf-plugins-core maven
      - export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
      - java -version
      - dnf config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - dnf install -y terraform

  pre_build:
    commands:
      - echo '========== BUILDING SPRING BOOT JAR =========='
      - export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version
      - cd Server
      - mvn clean package -DskipTests
      - cd ..

  build:
    commands:
      - echo '========== UPLOADING JAR TO S3 =========='
      - aws s3 cp Server/target/shop-0.0.1-SNAPSHOT.jar s3://gundam-hobby-shop-frontend-911784620581/app/hobby-shop-backend.jar
      - echo '========== TERRAFORM APPLY =========='
      - terraform init
      - terraform apply -auto-approve -input=false

  post_build:
    commands:
      - echo '========== DEPLOY COMPLETE =========='
