sonar.organization=nicholasmathias197
sonar.projectKey=nicholasmathias197_Hobby_Shop_App
sonar.projectName=Hobby_Shop_App
sonar.sources=Server/src/main/java
sonar.tests=Server/src/test/java
sonar.java.binaries=Server/target/classes
sonar.sourceEncoding=UTF-8
