# Development Profile
spring.datasource.url=jdbc:mysql://localhost:3306/hobby_shop_db_dev?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.com.hobby.shop=DEBUG